export const vehicleSchemas = {
  VehicleResponseDTO: {
    type: "object",
    properties: {
      id: { type: "string", format: "uuid" },
      fipeCode: { type: "string", nullable: true },
      value: { type: "number" },
      referenceMonth: { type: "integer" },
      referenceYear: { type: "integer" },
      vehicleYear: { type: "integer" },
      createdAt: { type: "string", format: "date-time" },
      updatedAt: { type: "string", format: "date-time" },
      modelId: { type: "string", format: "uuid" },
      fuelTypeId: { type: "string", format: "uuid" },
      createdById: { type: "string", format: "uuid", nullable: true },
      updatedById: { type: "string", format: "uuid", nullable: true },
      fuelType: { $ref: "#/components/schemas/FuelTypeResponseDTO" },
    },
    required: [
      "id",
      "value",
      "referenceMonth",
      "referenceYear",
      "vehicleYear",
      "createdAt",
      "updatedAt",
      "modelId",
      "fuelTypeId",
      "fuelType",
    ],
  },
};
